spring.application.name=commerce-backend

# DB CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/commerce_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER
server.port=8080
spring.security.user.name=admin
spring.security.user.password=123456

app.jwt.secret=12345678901234567890123456789012
app.jwt.expiration=86400000